# Generated by Django 5.2.15 on 2026-07-18 18:06

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Company description', null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.company_image_path, verbose_name='image company')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('subset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superset', to='products.categorymodel', verbose_name='subset')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('quantity', models.PositiveIntegerField(db_index=True, default=0, verbose_name='quantity')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='is available')),
                ('category', models.ManyToManyField(related_name='products', to='products.categorymodel', verbose_name='categories')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.companymodel', verbose_name='Company product')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path, verbose_name='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='SoldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name=' date create')),
                ('price', models.PositiveIntegerField(verbose_name='total price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solds', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='Price of the product at the time of placing the order', verbose_name='unit price')),
                ('total_price', models.PositiveIntegerField(help_text='We multiply the number of products and the unit price of the product.', verbose_name='total price')),
                ('quantity', models.PositiveIntegerField(help_text='Number of products in the order', verbose_name='quantity')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='products.productmodel', verbose_name='product')),
                ('sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='products.soldmodel', verbose_name='sold')),
            ],
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['name'], name='products_pr_name_d562ce_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['price'], name='products_pr_price_9f38cf_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['create_dt'], name='products_pr_create__5e2d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['quantity'], name='products_pr_quantit_8155b7_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['is_available'], name='products_pr_is_avai_897900_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together={('name', 'company')},
        ),
    ]
