# Generated by Django 5.2.15 on 2026-07-18 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='products.productmodel', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'product'], name='store_retur_user_id_c1c2a9_idx'), models.Index(fields=['create_dt'], name='store_retur_create__7016a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('is_available', models.BooleanField(default=False, verbose_name='is available')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_inventories', to='products.productmodel', verbose_name='product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='store_store_product_36a526_idx'), models.Index(fields=['create_dt'], name='store_store_create__155114_idx')],
                'constraints': [models.UniqueConstraint(fields=('product',), name='unique_product_store')],
            },
        ),
        migrations.CreateModel(
            name='TransfersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='products.productmodel', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'product'], name='store_trans_user_id_31c28f_idx'), models.Index(fields=['create_dt'], name='store_trans_create__c288ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='UpdatedInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'ویرایش'), ('DELETE', 'حذف'), ('TRANSFER', 'انتقال'), ('SOLD', 'فروش'), ('WASTE', 'ضایعات'), ('RETURN', 'مرجوعی')], db_index=True, max_length=20)),
                ('text', models.TextField(verbose_name='Updated information')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'create_dt'], name='store_updat_user_id_a8c8ee_idx'), models.Index(fields=['action_type'], name='store_updat_action__bee9c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('is_available', models.BooleanField(default=False, verbose_name='is available')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='products.productmodel', verbose_name='product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='store_wareh_product_d1971f_idx')],
                'constraints': [models.UniqueConstraint(fields=('product',), name='unique_product_warehouse')],
            },
        ),
        migrations.CreateModel(
            name='WasteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description ')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste', to='products.productmodel', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'indexes': [models.Index(fields=['create_dt'], name='store_waste_create__af5360_idx'), models.Index(fields=['product'], name='store_waste_product_7667ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('product',), name='unique_product_waste')],
            },
        ),
    ]
